name: Simple start

on: push

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
     - uses: actions/checkout@v1
       name: Setting up Latest Node 13.X
     - uses: actions/setup-node@v1
       with: 
          node-version: '13.x'
          run: npm install
       name: Node version installed
     - run: node -v
       name: changing directory into Kayode Angular App
     - run: cd my-app
       name: Displaying current dir
     - run: pwd
       
