name: Simple start

on: push

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
     - uses: actions/checkout@v1
       name: Setting up Latest Node 13.X
     - uses: actions/setup-node@v1
       with: 
          node-version: '13.x'
          run: npm install
       name: Installing Node 13
     - run: node -v
       name: Node version installed
     - run: cd my-app
       name: Change directory into Angular app my-app 
     - run: pwd
       name: Present working directory
     - run: ls -al
       name: List current directory
     - run: npm --prefix ./my-app/ install
       name: Npm install in my-app
       
