name: Simple start

on: push

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
     - uses: actions/checkout@v1
     - uses: actions/setup-node@v1
       with: 
          node-version: '13.x'
          run: npm install
       name: destiny
     - run: node -v
       
